#####################
## PROGMaxi & Bronek 
## TEPLOTA A VLHKOST - AM2302 (odpor cca 10kOhm), PIN D2 nebo GPIO16
## RYCHLOST VETRU - WH-SP-WS01, PIN D6 nebo GPIO12
## SMER VETRU - WH-SP-WD, PIN A0
## SRAZKOMER - MS-WH-SP-RG, PIN D7 nebo GPIO13
## TESTOVANO NA WEMOS D1 R1
## 
##### 
##### 
#####################
## Konfigurace ######
## A0 - SMER VETRU
## D0 - 
## D1 - 
## D2 - TEPLOTA A VLHKOST
## D3 - 
## D4 - 
## D5 - 
## D6 - RYCHLOST VETRU
## D7 - SRAZKOMER
## D8 - 
#####################
esphome:
  name: wx_station
  platform: ESP8266
  board: d1

wifi:
  networks:
  - ssid: Vergl2
    password: Hovnokleslo105
    priority: 0.09
  - ssid: Vergl
    password: Hovnokleslo105
    priority: 0.08
  - ssid: Cisco
    password: Hotentot1919
    priority: 0.07
  - ssid: Cisco
    password: Hotentot1919
    hidden: true
    priority: 0.00
  ap:
    ssid: "WStation"
    password: "Hotentot1919"
    ap_timeout: 5min

  
captive_portal:

logger:

api:
  password: "Hotentot1919"
  
ota:
  safe_mode: True
  password: "Hotentot1919"

i2c:
  frequency: 100kHz #try for longer distance - currently works at 50' - 1 pair per 5v, Gnd, SDA, SCL

sensor:

  - platform: dht
    pin: 
      number: GPIO16
    temperature:
      name: "TEPLOTA"
    humidity:
      name: "VLHKOST"
    update_interval: 30s      

  - platform: pulse_counter
    pin: 
      #pin D5
      number: GPIO12
      mode: INPUT_PULLUP
    unit_of_measurement: 'm/s'
    name: 'RYCHLOST_VETRU'
    icon: 'mdi:weather-windy'
    id: my_wind
    count_mode:
      rising_edge: DISABLE
      falling_edge: INCREMENT
    internal_filter: 50us
    update_interval: 60s 
    on_raw_value:
      then:
        - sensor.template.publish:
            id: template_sens
            state: !lambda "return x;"
    #rotations_per_sec = pulses/2/60
    #circ_m=0.09*2*3.14 = 0.5652
    #mps = 1.18*circ_m*rotations_per_sec  
    #mps = 1.18*0.5652/2/60 =0,0055578
    accuracy_decimals: 2
    filters:
      - multiply: 0.0055578
      - sliding_window_moving_average:
          window_size: 2
          send_every: 1

  - platform: pulse_counter
    pin:
      #pin D6
      number: GPIO13
      mode: INPUT_PULLUP
    unit_of_measurement: 'mm'
    name: 'SRAZKOMER'
    icon: 'mdi:weather-rainy'
    id: my_rain
    internal: true
    count_mode:
      rising_edge: DISABLE
      falling_edge: INCREMENT
    internal_filter: 50us
    update_interval: 9s
    filters:
      - multiply: 0.2794
    accuracy_decimals: 3

  - platform: template
    name: "Template Sensor"
    id: template_sens
    filters:
#      - multiply: 0.2794
#      - multiply: 60 (to get mm/h)
      - multiply: 16.764
      - sliding_window_moving_average:
          window_size: 60
          send_every: 1

  - platform: integration
    name: "SRAZKY_ZA_MINUTU"
    id: rain_per_min
    time_unit: min
    unit_of_measurement: 'mm'
    sensor: my_rain
    
  - platform: total_daily_energy
    name: "SRAZKY_ZA_DEN"
    power_id: my_rain
    unit_of_measurement: 'mm'
    icon: 'mdi:weather-rainy'
    filters:
      - multiply: 60

  - platform: adc
    id: adc_sensor
    pin: A0
    name: ADC
    internal: true
    update_interval: 60s
    filters:
      # - multiply: 3.3 ##built into Wemos
      #- multiply: 0.0009775171   #1/1023
    accuracy_decimals: 3 ##IMPORTANT to get resolution for resistance sensor

  - platform: resistance
    sensor: adc_sensor
    id: resistance_sensor
    configuration: DOWNSTREAM
    resistor: 11.8kOhm
    internal: true
    name: "STANICE_ODPOR"
    accuracy_decimals: 1
    filters:
      - heartbeat: 90s #thinking of increasing interval to plot better
    on_value:
      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 3400
              below: 3700
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "S"
            - sensor.template.publish:
                id: wind_heading
                state: 360.0
                
      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 4000
              below: 4400
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "SZ"         
            - sensor.template.publish:
                id: wind_heading
                state: 315.0            
      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 4800
              below: 4500
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "Z"                
            - sensor.template.publish:
                id: wind_heading
                state: 270.0          
      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 2400
              below: 2800
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "JZ"    
            - sensor.template.publish:
                id: wind_heading
                state: 225.0             
      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 800
              below: 1200
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "J"    
            - sensor.template.publish:
                id: wind_heading
                state: 180.0            
      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 500
              below: 700
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "JV"    
            - sensor.template.publish:
                id: wind_heading
                state: 135.0              
      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 100
              below: 400
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "V"    
            - sensor.template.publish:
                id: wind_heading
                state: 90.0          
      - if:
          condition:
            sensor.in_range:
              id: resistance_sensor
              above: 1500
              below: 1900
          then:
            - text_sensor.template.publish:
                id: wind_dir_card
                state: "SV"    
            - sensor.template.publish:
                id: wind_heading
                state: 45.0

  - platform: template
    name: "UHEL_VETRU"
    id: wind_heading
    unit_of_measurement: "°"

  - platform: homeassistant
    name: "VITR_3M"
    id: wind_3m_avg
    internal: true 
    unit_of_measurement: "km/h"
    entity_id: sensor.wx_sta_wind_stats  

  - platform: homeassistant
    id: wind_60m_gust
    internal: true 
    unit_of_measurement: "km/h"
    entity_id: sensor.wx_sta_wind_60m_stats    

text_sensor:
  - platform: template
    name: "SMER_VETRU"
    id: wind_dir_card

  - platform: wifi_info
    ip_address:
      name: Wx_sta IP Address
    mac_address:
      name: Wx_Sta Mac Wifi Address

time:
  - platform: homeassistant
    id: my_time